### ISSUE TITLE
MVPリリースレビュー

### ISSUE THREAD

**Issue by shurijoc** [fujii-kosuke-36/summer_festival#29]
こちらにレビュー内容書かせていただきます！
就活を踏まえて、以下の観点からレビューさせていただきますね。

サービスとREADMEを元にレビューします。

```
💡 就活レビュー観点

1. 課題に対してサービス内で適切な解決策となる機能を提供できているか・READMEに書いているか
2. 就活において十分な技術力を示せる機能を実装しているか
3. UIでユーザーが迷わないような導線を作れているか・ユーザーが使いたくなるようなサービス設計ができているか
```

## 1について
就活では「課題に対して、適切な仮説を立てて、その仮説に対して妥当な解決方法を機能として実装しているか」というところは技術力と同じくらい重要です。

READMEに書いてある課題と解決策を元に「課題・仮説・解決策」を3点セットで書いてください！
現状のままだと何を解決したいサービスなのか少し曖昧なので。

## 2について

> ・spotify-apiのパラメーターを使った独自のレコメンド機能 
  　（現状考えているのはenergy numberを使って元気な曲の提供）
> ・OGP

こちら実装予定ということで、実装されるのであれば技術力に関しては良いかなと思います！
ただしレコメンドに関してはこのサービスの技術アピールにおいて重要な役割を担っているのでアーティスト一覧でモーダル表示など全部のユーザーの目に留まる用にしてください。

## 3について

全体の世界観をまずは統一させましょう！「フェス」または「アーティスト」をベースにしているサービスということを前提に気になった箇所をフィードバックさせていただきます。
ちょっと多いですが1つずつは軽い変更で、印象がかなり変わるものです 🙏 

https://school.runteq.jp/v2/mypage/helps/articles/design_tips?gretel_word=%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3 こちらの記事も合わせて読んでみてください！エンジニアになってからも使える知識です。

1. トップのファーストビューの背景画像が暗い海なので変更する（フェス = 夏 = 海だとしてももう少し明るさが欲しい + もっと直接的にフェス感あるものが良いです！）
2. https://fest-hunt.herokuapp.com/users/new のラベルが英語なので日本語にする
3. ヘッダーに野外フェスターとFest-Huntが混ざっているので統一する
4. https://fest-hunt.herokuapp.com/bookmarks で何もお気に入りがない場合、何も表示されないのでアーティスト一覧へのリンクを追加する
5. ボタンと背景色のトンマナが揃っておらず浮いている感じがするので背景は白などにする
6. すべての画面で横幅を目一杯使っており間延びしている印象です。tailwindのgridを適用させて横にマージンをもたせましょう。

少し長くなりましたがご確認をお願いします！
UIは就活で面接官が一番最初に見るところです。ちょっとした配置、文字の大きさで印象が変わるので整えるようにしましょう！

以上長いですがご確認をお願いします！

**Comment by fujii-kosuke-36** [comment]
レビューありがとうございます。
１つずつ改善していきます。

**Comment by shurijoc** [comment]
ありがとうございます。上記スッキリしてとても良いと思います。

その「課題・仮説・解決策」であれば「フェスを選ぶ→フェスの出場するアーティストを表示する→音楽を聴ける」というユースフローを作ったほうが良いかと思います。

これならフェスの予習にとても役立つサービスになります！

現状のページ・データ構造からそこまで大きく変えずともできるかなと。
https://fest-hunt.herokuapp.com/festivals/1 などの詳細にアーティスト一覧とその楽曲を表示するイメージです。

**Comment by shurijoc** [comment]
@fujii-kosuke-36 

UIについては良いと思います！

https://github.com/fujii-kosuke-36/summer_festival/issues/29#issuecomment-1539724417

こちらの箇所いかがでしょうか？
MVPリリースはして、本リリースまでに機能としては実装するというスケジュール感で考えています。
